/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_spi_api_SpiJNITransfer */

#ifndef _Included_android_spi_api_SpiJNITransfer
#define _Included_android_spi_api_SpiJNITransfer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     android_spi_api_SpiJNITransfer
 * Method:    test
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_android_1spi_1api_SpiJNITransfer_test
  (JNIEnv *, jobject);

/*
 * Class:     android_spi_api_SpiJNITransfer
 * Method:    open
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_android_1spi_1api_SpiJNITransfer_open
  (JNIEnv *, jobject, jstring);

/*
 * Class:     android_spi_api_SpiJNITransfer
 * Method:    transfer
 * Signature: (I[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_android_1spi_1api_SpiJNITransfer_transfer
  (JNIEnv *, jobject, jint, jbyteArray);

/*
 * Class:     android_spi_api_SpiJNITransfer
 * Method:    close
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_android_1spi_1api_SpiJNITransfer_close
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
